### ISSUE TITLE
test_layer_file fails

### ISSUE THREAD

**Issue by nickrsan** [ucd-cws/arcpy_metadata#23]
test_layer_file fails with the following traceback on Python 2.7:

Error
Traceback (most recent call last):
  File "C:\Users\nrsantos\Code\arcpy_metadata\tests\test_metadata_editor.py", line 103, in test_layer_file
    self._run_example(os.path.join(test_data_folder, r"layer.lyr"))
  File "C:\Users\nrsantos\Code\arcpy_metadata\tests\test_metadata_editor.py", line 41, in _run_example
    metadata = md.MetadataEditor(feature_class)  # also has a feature_layer parameter if you're working with one, but edits get saved back to the source feature class
  File "C:\Users\nrsantos\Code\arcpy_metadata\arcpy_metadata\metadata_editor.py", line 74, in __init__
    self.data_type = desc.dataElement.dataType
AttributeError: DescribeData: Method dataElement does not exist

**Comment by nickrsan** [comment]
Thomas, I added you before I pushed the commit that closed this, just in case you had a moment to review it. I swapped "Layer" from the list of _layers to _simple_datasets - since layer files don't have data sources, it was causing the old code to fail when it went to retrieve the "true source" like it does with feature layers. After moving it to _simple_datasets, it acts appropriately, operating directly on the metadata of the layer file, and the test suite passes. If you don't get a chance to look, no worries, but I wanted to call your attention to the change.
